# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-30 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.CharField(max_length=20, verbose_name='\u5f53\u524d\u6b63\u5728\u4f7f\u7528\u7684\u7528\u6237')),
                ('last_user', models.CharField(max_length=20, verbose_name='\u4e0a\u4e00\u6b21\u4f7f\u7528\u7684\u7528\u6237')),
                ('mobile_type', models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('type', models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u5206\u7c7b')),
                ('number', models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u578b\u53f7')),
                ('color', models.CharField(max_length=20, verbose_name='\u8bbe\u5907\u989c\u8272')),
                ('sn', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8bbe\u5907SN\u7801')),
                ('mobile_state', models.CharField(choices=[('use', '\u4f7f\u7528'), ('free', '\u7a7a\u95f2')], default='free', max_length=20, verbose_name='\u624b\u673a\u72b6\u6001')),
                ('remark', models.TextField(verbose_name='\u5907\u6ce8')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u501f\u7528\u8bb0\u5f55',
                'verbose_name_plural': '\u8bbe\u5907\u501f\u7528\u8bb0\u5f55',
            },
        ),
    ]
