# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileinfo',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bbe\u5907\u989c\u8272'),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='current_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5f53\u524d\u6b63\u5728\u4f7f\u7528\u7684\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='last_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4e0a\u4e00\u6b21\u4f7f\u7528\u7684\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='mobile_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8bbe\u5907\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8bbe\u5907\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8bbe\u5907\u5206\u7c7b'),
        ),
    ]
