# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20171017_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileinfo',
            name='mobile_state',
            field=models.CharField(choices=[('use', '\u4f7f\u7528'), ('free', '\u7a7a\u95f2'), ('songshen', '\u9001\u5ba1')], default='free', max_length=20, verbose_name='\u624b\u673a\u72b6\u6001'),
        ),
    ]
