# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-24 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20171017_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u7528\u6237')),
                ('operation', models.CharField(max_length=20, verbose_name='\u64cd\u4f5c')),
                ('entity', models.CharField(max_length=100, verbose_name='\u64cd\u4f5c\u5b9e\u4f53')),
                ('operation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u64cd\u4f5c\u53d1\u751f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u501f\u7528\u65e5\u5fd7\u8bb0\u5f55',
                'verbose_name_plural': '\u8bbe\u5907\u501f\u7528\u65e5\u5fd7\u8bb0\u5f55',
            },
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='mobile_state',
            field=models.CharField(choices=[('use', '\u4f7f\u7528'), ('free', '\u7a7a\u95f2')], default='free', max_length=20, verbose_name='\u624b\u673a\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='\u8bbe\u5907SN\u7801'),
        ),
    ]
